### ISSUE TITLE
差不多200了啊！赶紧来更新

### ISSUE THREAD

**Issue by anson1007** [super-l/superl-url#10]
赶紧来更新啊！！！
把redis跟mysql搞上去啊！！！！
有轮子啊！！！！

**Comment by vuatph** [comment]
201 了，赶紧来更新！

**Comment by super-l** [comment]
OK。这几天就开始更新！

**Comment by super-l** [comment]
> 201 了，赶紧来更新！

已经开始

**Comment by super-l** [comment]
> 赶紧来更新啊！！！
> 把redis跟mysql搞上去啊！！！！
> 有轮子啊！！！！

此次升级，主要是修复BUG，兼容性以及提升运行效率
