### ISSUE TITLE
请哪如何保留http://这个前缀

### ISSUE THREAD

**Issue by dengwen168** [super-l/superl-url#3]
您好，我使用时选择“去除URL参数”，
采集到的网址结果是没有http://这个前缀的，
请问一下在哪里可以修改代码保留http://这个前缀？
谢谢。。

**Comment by super-l** [comment]
请查看"script"目录下的各个搜索引擎模块，找到下面代码，logfile.write()就是实现写入的，你可以手工把"http://"固定加在前面。

                            if self.write_title:
                                if self.write_name:
                                    logfile.write(self.search_name + realurl+'    '+title+'\n')
                                else:
                                    logfile.write(realurl+'    '+title+'\n')
                            else:
                                if self.write_name:
                                    logfile.write(self.search_name+realurl+'\n')
                                else:
                                    logfile.write(realurl+'\n')

**Comment by dengwen168** [comment]
非常感谢。。
