### ISSUE TITLE
为什么在kali linux下直接./super-url.py 可以截图??

### ISSUE THREAD

**Issue by threst** [super-l/superl-url#4]
rt

**Comment by super-l** [comment]
请具体描述一下问题，没有理解你的意思。测试环境是在mac的shell下的

**Comment by threst** [comment]
我在kali下直接./super-url.py,鼠标就会变成十字，可以选择屏幕区域进行截图

**Comment by super-l** [comment]
不是这样运行的。./xxx.sh  这种运行方法是针对shell脚本。Python的请使用python xxx.py

**Comment by super-l** [comment]
不是这样运行的。Python的请使用python xxx.py，而不是./xxx.py

**Comment by threst** [comment]
我知道是python 这样运行，可是下下来xxx.py是可执行权限，所以我尝试了下./xx.py
